[package]
name = "firecrab-bench"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "firecrab-bench"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
firecrab-api-types = { path = "../firecrab-api-types" }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "blocking", "json"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { version = "0.3", features = ["formatting"] }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
mockito = "1"
