// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateVmRequest = { name: string, template: string, ram: number, cpu: number, };
