// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EgressPolicy } from "./EgressPolicy";
import type { PortForward } from "./PortForward";

export type CreateVmRequest = {
  name: string;
  template: string;
  ram: number;
  cpu: number;
  diskGb: number;
  egressPolicy: EgressPolicy;
  microNetworkId: string;
  storageRoot: string | null;
  /** Optional Shell repository ids; latest revision pinned at create. */
  shellIds?: Array<string>;
  /** Inbound port forwarding rules (DNAT). */
  portForwards?: Array<PortForward>;
  /** Per-VM environment applied on the next start. Omitted = {}. */
  env?: { [key: string]: string };
};
