// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EgressPolicy } from "./EgressPolicy";

export type CreatePoolRequest = {
  name: string;
  /** Installed image alias; the pool pins the version it resolves to now. */
  template: string;
  cpu: number;
  ram: number;
  diskGb: number;
  egressPolicy: EgressPolicy;
  microNetworkId: string;
  storageRoot: string | null;
  /** Members kept booted and unleased. */
  minReady: number;
  /** Ceiling on members in any state, leased and draining included. */
  maxSize: number;
  leaseTtlSeconds: number;
};
