// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HostStatusResponse = {
  loadAverage1m: number,
  memoryTotalMib: number,
  memoryAvailableMib: number,
  diskTotalGib: number,
  diskAvailableGib: number,
  uptimeSeconds: number,
};
