// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MicroStorageVm } from "./MicroStorageVm";

export type MicroStorageDetailResponse = {
  id: string;
  name: string;
  path: string;
  availableGib: number;
  totalGib: number;
  vms: Array<MicroStorageVm>;
};
