// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MicroNetworkBridge } from "./MicroNetworkBridge";
import type { MicroNetworkFirewall } from "./MicroNetworkFirewall";
import type { MicroNetworkNat } from "./MicroNetworkNat";
import type { MicroNetworkSubnet } from "./MicroNetworkSubnet";
import type { MicroNetworkVm } from "./MicroNetworkVm";

export type MicroNetworkDetailResponse = { id: string, name: string, subnet: MicroNetworkSubnet, bridge: MicroNetworkBridge, nat: MicroNetworkNat, firewall: MicroNetworkFirewall, vms: Array<MicroNetworkVm>, };
