// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VmState } from "./VmState";

export type MicroStorageVm = { id: string, name: string, state: VmState, diskGb: number, };
