// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EgressPolicy } from "./EgressPolicy";

export type MicroNetworkFirewall = { eastWestBlocked: boolean, crossNetworkBlocked: boolean, antiSpoofing: boolean, defaultEgress: EgressPolicy, };
