// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PoolLeaseState } from "./PoolLeaseState";
import type { VmResponse } from "./VmResponse";

export type PoolLeaseResponse = {
  id: string;
  poolId: string;
  vmId: string;
  state: PoolLeaseState;
  acquiredAtMs: number;
  expiresAtMs: number;
  endedAtMs?: number;
  /** The leased VM while it exists. */
  vm?: VmResponse;
};
