// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PoolMemberState } from "./PoolMemberState";

export type PoolMemberResponse = { vmId: string, state: PoolMemberState, createdAtMs: number, };
