// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EgressPolicy } from "./EgressPolicy";
import type { PoolMemberResponse } from "./PoolMemberResponse";

export type PoolResponse = {
  id: string;
  name: string;
  template: string;
  /** Image version every member boots. */
  templateVersion: string;
  cpu: number;
  ram: number;
  diskGb: number;
  egressPolicy: EgressPolicy;
  microNetworkId: string;
  storageRoot: string;
  minReady: number;
  maxSize: number;
  leaseTtlSeconds: number;
  /** Set by DELETE; the pool disappears once its members are gone. */
  deleting: boolean;
  members: Array<PoolMemberResponse>;
  /** Most recent failure creating or booting a member. */
  lastError?: string;
  createdAtMs: number;
};
