// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StartupStep } from "./StartupStep";
import type { StartupStepOutcome } from "./StartupStepOutcome";

export type StartupStepRun = { step: StartupStep, startedAtMs: number, endedAtMs: number | null, outcome: StartupStepOutcome, detail: string | null, };
