// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StorageDeviceResponse = {
  device: string;
  mountpoint: string;
  fstype: string;
  sizeGib: number;
  availableGib: number;
  kind: string;
};
