// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StorageRootResponse = {
  id: string;
  name: string;
  path: string;
  availableGib: number;
  totalGib: number;
  kind: string;
};
