// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EgressPolicy } from "./EgressPolicy";

export type UpdateVmResourcesRequest = { ram: number, cpu: number, diskGb: number, egressPolicy: EgressPolicy, };
