// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EgressPolicy } from "./EgressPolicy";
import type { StartupStep } from "./StartupStep";
import type { StartupStepRun } from "./StartupStepRun";
import type { VmState } from "./VmState";
import type { VmUsageSample } from "./VmUsageSample";

export type VmResponse = {
  id: string,
  name: string,
  state: VmState,
  template: string,
  templateVersion: string,
  cpu: number,
  ram: number,
  diskGb: number,
  startupStep: StartupStep | null,
  startupTimeline: Array<StartupStepRun>,
  egressPolicy: EgressPolicy,
  ipv4: string | null,
  mac: string | null,
  hostname: string,
  microNetworkId: string,
  storageRoot: string,
  /** Guest OS CPU busy % from Guest Agent; null until reported. */
  cpuUsagePercent: number | null,
  /** Guest used memory MiB; null until reported. */
  memoryUsedMib: number | null,
  /** Guest MemTotal MiB; null until reported. */
  memoryTotalMib: number | null,
  /** Guest used memory % of MemTotal; null until reported. */
  memoryUsedPercent: number | null,
  /** Recent guest-agent samples for sparklines. */
  usageHistory: Array<VmUsageSample>,
};
