// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EgressPolicy } from "./EgressPolicy";
import type { PackageUpdateStatus } from "./PackageUpdateStatus";
import type { StartupStep } from "./StartupStep";
import type { StartupStepRun } from "./StartupStepRun";
import type { VmState } from "./VmState";

export type VmResponse = { id: string, name: string, state: VmState, template: string, templateVersion: string, cpu: number, ram: number, diskGb: number, startupStep: StartupStep | null, startupTimeline: Array<StartupStepRun>, egressPolicy: EgressPolicy, packageUpdate: PackageUpdateStatus | null, ipv4: string | null, mac: string | null, hostname: string, microNetworkId: string, storageRoot: string, };
