// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EgressPolicy } from "./EgressPolicy";
import type { StartupStep } from "./StartupStep";
import type { VmState } from "./VmState";

export type VmResponse = { id: string, name: string, state: VmState, template: string, templateVersion: string, cpu: number, ram: number, diskGb: number, startupStep: StartupStep | null, egressPolicy: EgressPolicy, ipv4: string | null, mac: string | null, hostname: string, };
