// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VmUsageSample = {
  atMs: number,
  /** Guest CPU busy percent. */
  cpuUsagePercent: number | null,
  /** Guest used memory MiB. */
  memoryUsedMib: number | null,
  /** Guest total memory MiB. */
  memoryTotalMib: number | null,
  /** Guest used memory percent of MemTotal. */
  memoryUsedPercent: number | null,
};
