// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VmUsageSample = {
  /** Unix epoch milliseconds when the sample was taken. */
  atMs: number,
  /** Guest CPU busy percent for the interval ending at this sample. */
  cpuUsagePercent: number | null,
  /** Guest used memory in MiB at this sample. */
  memoryUsedMib: number | null,
  /** Guest total memory in MiB at this sample. */
  memoryTotalMib: number | null,
  /** Guest used memory percent of MemTotal at this sample. */
  memoryUsedPercent: number | null,
};
